CXX = g++
CXXFLAGS = -IInclude -std=c++17
SRC = Src/Main.cpp Utils/Utils.cpp
OBJS = $(SRC:.cpp=.o)
EXEC = Self

all: $(EXEC)

$(EXEC): $(OBJS)
	$(CXX) $(CXXFLAGS) -o $@ $^

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	rm -f $(OBJS) $(EXEC)
